package co.edu.uniquindio.analizador.lexico

/**
 * Enumeración que representa una categoría léxica
 *
 */
enum class Categoria {

    ENTERO, REAL, DECIMAL, IDENTIFICADOR, PALABRA_RESERVADA, OPERADOR_ARITMETICO,OPERADOR_RELACIONAL, OPERADOR_LOGICO,
    ASIGNACION, INCREMENTO, DECREMENTO,PARENTESIS_IZQUIERDO, PARENTESIS_DERECHO,LLAVE_IZQUIERDA, LLAVE_DERECHA,
    FIN_SENTENCIA, SEPARADOR,HEXADECIMAL, CADENA_CARACTERES, COMENTARIO_LINEA,COMENTARIO_BLOQUE

}
